const BUG_TYPE_COLOR = '#729F3F';
const GRASS_TYPE_COLOR = '#9BCC50';
const POISON_TYPE_COLOR = '#B97FC9';
const FIRE_TYPE_COLOR = '#FD7D23';
const FLYING_TYPE_COLOR = '#3DC7EF';
const WATER_TYPE_COLOR = '#4592C4';
const NORMAL_TYPE_COLOR = '';
const ELETRIC_TYPE_COLOR = '#EED534';
const GROUND_TYPE_COLOR = '#AB9842';
const FAIRY_TYPE_COLOR = '#FDB9E9';
const FIGHTING_TYPE_COLOR = '#D56724';
const PSYCHIC_TYPE_COLOR = '#F366B9';
const ROCK_TYPE_COLOR = '#A38C20';

export const typeColors = {
  Bug: BUG_TYPE_COLOR,
  Grass: GRASS_TYPE_COLOR,
  Poison: POISON_TYPE_COLOR,
  Fire: FIRE_TYPE_COLOR,
  Flying: FLYING_TYPE_COLOR,
  Water: WATER_TYPE_COLOR,
  Normal: NORMAL_TYPE_COLOR,
  Electric: ELETRIC_TYPE_COLOR,
  Ground: GROUND_TYPE_COLOR,
  Fairy: FAIRY_TYPE_COLOR,
  Fighting: FIGHTING_TYPE_COLOR,
  Psychic: PSYCHIC_TYPE_COLOR,
  Rock: ROCK_TYPE_COLOR,
};
